### ISSUE TITLE
Resolve complete source path when parsing Spotbugs xml file

### ISSUE THREAD

**Issue by terje2001** [tomasbjerre/violations-lib#105]
As far as I can see, the spotbugs xml file will list all known source directories at the top, under multiple "<SrcDir>..</SrcDir>' tags. Later, when referencing a source file, the "sourcepath" attribute is relative to any one of the above 'SrcDir' entries.

When violations-lib produces its output (in my case code-climate-report.json), would it be possible to have violations-lib resolve the correct full path for the source file, rather than just copying the value across? I assume this would require actual filesystem operations to see which 'SrcDir' is actually containing the file.

This would help later parsing of the json file to actually have it correct. As far as I can see, the SpotBugs will always create relative.

**Comment by tomasbjerre** [comment]
I don't want file operations in the parsers. But it should be possible to add in the codeclimate transformer:
https://github.com/tomasbjerre/violations-lib/blob/d8c2e0c0851f8cc46d71436baeb2d7b0668d93c8/src/main/java/se/bjurr/violations/lib/model/codeclimate/CodeClimateTransformer.java#L27

It is the `location` attribute in the codeclimate report you want to be absolute?

**Comment by tomasbjerre** [comment]
no response
