### ISSUE TITLE
Add rule to code climate report

### ISSUE THREAD

**Issue by sniperrifle2004** [tomasbjerre/violations-lib#112]
I am using the violations-maven-plugin to generate code-climate reports, but am missing an analogue to the rule field in the resulting report.

Thinking that such a field should logically exist, I have checked https://developer.codeclimate.com/#get-issues and it seems to me that check_name is supposed to contain the rule name, while engine_name should contain the Reporter. Is there any objection to making this change?

**Comment by tomasbjerre** [comment]
Releasing fix now.
