### ISSUE TITLE
Support mypy

### ISSUE THREAD

**Issue by tuukkamustonen** [tomasbjerre/violations-lib#13]
https://pypi.python.org/pypi/mypy-lang is static checker for python 3 type annotations. Example output:

```
fs/cs/backend/log.py: note: In member "filter" of class "CsLogFilter":
fs/cs/backend/log.py:16: error: "LogRecord" has no attribute "user_uuid"
fs/cs/backend/log.py:17: error: "LogRecord" has no attribute "tenant_id"
fs/cs/backend/errorhandler.py: note: In member "__init__" of class "CsErrorHandler":
fs/cs/backend/errorhandler.py:16: error: The return type of "__init__" must be None
fs/cs/backend/api.py: note: At top level:
fs/cs/backend/api.py:23: error: ContextManager[Any] not callable
tests/test_schema.py:864: error: Name 'test_nested_only_and_exclude' already defined
```

I have used `^(.*):(\d+): (.*): (.*)$` regex with warning plugin:

```groovy
String fileName = matcher.group(1)
String lineNumber = matcher.group(2)
String category = matcher.group(3)
String message = matcher.group(4)
```

**Comment by tomasbjerre** [comment]
It should be released in all plugins now. Open issue again if any problems!

**Comment by tuukkamustonen** [comment]
Thanks for super-fast actions again! Will test it tomorrow.

Btw. clicking the commit to https://github.com/tomasbjerre/violations-lib/commit/31b2ded01433fb8 in https://github.com/tomasbjerre/violations-lib/blob/master/CHANGELOG.md leads to 404.

**Comment by tomasbjerre** [comment]
I updated the changelog now!

**Comment by tuukkamustonen** [comment]
Just installed the latest 1.43 (and restarted), but I don't see the new parsers in listing:

![image](https://cloud.githubusercontent.com/assets/94327/22682796/7e544dd8-ed1d-11e6-96f0-90a7c4a5e54e.png)

Would it be cool if plugins auto-discovered automatic parsers in violations-lib - so you wouldn't need to update anything in plugin side (expect lib dependency version)?

**Comment by tomasbjerre** [comment]
If you create a new job it will show up right? It should be auto discovered
but perhaps that only works for new jobs. Or if you remove and add the
build step.

Den 7 feb. 2017 09:10 skrev "Tuukka Mustonen" <notifications@github.com>:

**Comment by tuukkamustonen** [comment]
True, either removing/re-adding or adding to a new job shows the new parsers.

**Comment by tuukkamustonen** [comment]
Updated my job via Job DSL plugin and new parsers appeared correctly.
