### ISSUE TITLE
`CodeClimateParser` should map `check_name` to `rule`

### ISSUE THREAD

**Issue by remal** [tomasbjerre/violations-lib#132]
`CodeClimate` class has `check_name` field that is supposed to handle rule name:
https://github.com/tomasbjerre/violations-lib/blob/f24f5293544ae9f9886de267140819d3e9cb0884/src/main/java/se/bjurr/violations/lib/model/codeclimate/CodeClimate.java#L18

However, `CodeClimateParser` doesn't handle `check_name` field:
https://github.com/tomasbjerre/violations-lib/blob/f24f5293544ae9f9886de267140819d3e9cb0884/src/main/java/se/bjurr/violations/lib/parsers/CodeClimateParser.java#L48-L56

Could you please add `check_name` to `rule` mapping?

**Comment by tomasbjerre** [comment]
fixed, open issue again if any problems.
