### ISSUE TITLE
`CodeClimateParser` should map `engine_name` to `reporter`

### ISSUE THREAD

**Issue by remal** [tomasbjerre/violations-lib#133]
`CodeClimate` class has `engine_name` field that is supposed to handle a tool name that generated the violation:
https://github.com/tomasbjerre/violations-lib/blob/f24f5293544ae9f9886de267140819d3e9cb0884/src/main/java/se/bjurr/violations/lib/model/codeclimate/CodeClimate.java#L20

However, `CodeClimateParser` doesn't handle `engine_name` field at all and just sets `CODECLIMATE` string as a tool name:
https://github.com/tomasbjerre/violations-lib/blob/f24f5293544ae9f9886de267140819d3e9cb0884/src/main/java/se/bjurr/violations/lib/parsers/CodeClimateParser.java#L48-L56

Could you please add `engine_name` to `reporter` mapping?

**Comment by tomasbjerre** [comment]
fixed, open issue again if any problems.
