### ISSUE TITLE
Documentation: SARIF: Only v2.x is supported, analysis fails with SARIF v1.x files

### ISSUE THREAD

**Issue by jachstet-sea** [tomasbjerre/violations-lib#147]
The SARIF support in this library is awesome. However, it fails with SARIF v1.x files:
```
Parsing of file 'C:\FooBar.sarif' failed due to an exception:
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 17 column 23 path $.runs[0].results[0].message
```

The Microsoft Visual C# Compiler generates v1.x files by default (CLI switch `ErrorLog=BuildErrors.sarif`). But you can force it to generate SARIF v2.x using `ErrorLog="BuildErrors.sarif,version=2"`. I think this fact (v1.x not supported) and the workaround at least for the C# compiler should be documentated somewhere.

**Comment by tomasbjerre** [comment]
Thanks. I'm updating the docs with this.
