### ISSUE TITLE
ErrorProne parser fails on Windows paths

### ISSUE THREAD

**Issue by tnl-tbi** [tomasbjerre/violations-lib#153]
The colon after the drive letter in Windows paths conflicts with the current regex. For example no violations are found in the following input:
```
C:\proj\src\main\java\Test.java:12: warning: [NullAway] returning @Nullable expression from method with @NonNull return type
            return null;
            ^
    (see http://t.uber.com/nullaway )
1 warning
```

**Comment by tomasbjerre** [comment]
The ErrorProne parser is working very bad. I might actually remove it. There is an issue here to provide a better parsable format: https://github.com/google/error-prone/issues/444
