### ISSUE TITLE
SARIF 2.1.0 toolExecutionNotifications, toolConfigurationNotifications

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [tomasbjerre/violations-lib#154]
I'd like [SarifParser](https://github.com/tomasbjerre/violations-lib/blob/1.149.2/src/main/java/se/bjurr/violations/lib/parsers/SarifParser.java) to convert also the `notification` objects ([SARIF-v2.1.0 §3.58](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317894)) in the `invocation.toolExecutionNotifications` property ([SARIF-v2.1.0 §3.20.21](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317588)) and the `invocation.toolConfigurationNotifications` property ([SARIF-v2.1.0 §3.20.22](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317589)). Currently, it converts only the `result` objects ([SARIF-v2.1.0 §3.27](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317638)) in the `run.results` property ([SARIF-v2.1.0 §3.14.23](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317507)) and ignores the `notification` objects.

This would be particularly useful for `invocation.toolConfigurationNotifications` caused by an incorrect setting in a configuration file, as the [Warnings Next Generation plugin in Jenkins](https://plugins.jenkins.io/warnings-ng/) would then be able to to display the configuration file and pinpoint the error, if the SARIF log contains this information.

SarifParser currently reads the following properties of `result` objects: `ruleId`, `message`, `level`, and `locations`. Almost all of these correspond to identically-named properties in `notification` objects. However, the `result.ruleId` property has no direct equivalent. Instead, SarifParser would have to read a `reportingDescriptorReference` object from the `notification.descriptor` property and look up the rule based on that. After this has been implemented, it would be easy to add support for the `result.rule` property as well.

<details><summary>Sample SARIF 2.1.0 log with <code>toolConfigurationNotifications</code></summary>

```JSON
{
  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "demo",
          "version": "1.0.42",
          "rules": [],
          "notifications": [
            {
              "id": "DE0019",
              "name": "CannotCopyFromNonFileUri",
              "defaultConfiguration": {
                "level": "warning"
              }
            }
          ]
        }
      },
      "invocations": [
        {
          "toolConfigurationNotifications": [
            {
              "descriptor": {
                "index": 0
              },
              "locations": [
                {
                  "physicalLocation": {
                    "artifactLocation": {
                      "uri": "config.xml",
                      "uriBaseId": "CWD"
                    },
                    "region": {
                      "startLine": 290,
                      "startColumn": 17
                    }
                  }
                },
                {
                  "physicalLocation": {
                    "artifactLocation": {
                      "uri": "http://example.org/image.png"
                    }
                  }
                }
              ],
              "message": {
                "text": "Cannot copy from non-file URI: http://example.org/image.png"
              },
              "level": "warning",
              "timeUtc": "2022-07-18T17:54:13.412202Z"
            }
          ],
          "executionSuccessful": true
        }
      ],
      "originalUriBaseIds": {
        "CWD": {
          "uri": "file:///home/demo/"
        }
      },
      "specialLocations": {
        "displayBase": {
          "uri": "",
          "uriBaseId": "CWD"
        }
      },
      "results": [],
      "columnKind": "utf16CodeUnits"
    }
  ]
}
```
</details>

_edit: in `toolExecutionNotifications` and `toolConfigurationNotifications`, the `notification.descriptor` property refers to `toolComponent.notifications` rather than `toolComponent.rules`, according to [SARIF-v2.1.0 §3.52.3](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317865)_

**Comment by tomasbjerre** [comment]
Putting this on my todo.

**Comment by tomasbjerre** [comment]
I am releasing this now. Open issue again if any problems!

**Comment by tomasbjerre** [comment]
I think I have this fixed now. I tried to implement the `reportingDescriptor` lookup, but without example reports it is likely to contain bugs.

Should be no problem adding things from the `toolComponent` now, just open an issue with what you need.
