### ISSUE TITLE
Category from Roslyn SARIF 2.1.0 log

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [tomasbjerre/violations-lib#155]
Make [SarifParser](https://github.com/tomasbjerre/violations-lib/blob/8160e8a5062dc8bd529e8a2f38c478907d106577/src/main/java/se/bjurr/violations/lib/parsers/SarifParser.java) read the `properties.category` property that [the Roslyn compiler can write](https://github.com/dotnet/roslyn/blob/432d17a83aa5623e4581756f4d642997048056bd/src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs#L211-L217) into reportingDescriptor objects in SARIF 2.1.0 logs, and call [ViolationBuilder.setCategory](https://github.com/tomasbjerre/violations-lib/blob/8160e8a5062dc8bd529e8a2f38c478907d106577/src/main/java/se/bjurr/violations/lib/model/Violation.java#L78-L81) if the value is a string.

The SARIF 2.1.0 standard does not specify the format or meaning of the `properties.category` property. It just says that `properties` is allowed there and the value is a property bag ([section 3.8](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317448)). Regardless, if `properties.category` is there and has a string value, then I think it is better to use it than leave the category unset.

Taxonomies ([section 3.19.3](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317536)) are a similar concept that is more rigorously defined in the SARIF 2.1.0 standard. However, because each diagnostic rule can have relationships to multiple taxa (in the same taxonomy or in separate taxonomies), it would not be obvious how to choose just one taxon as the category of a Violation. Also, Roslyn never writes any reportingDescriptorRelationship objects to SARIF logs. For those reasons, I'm not proposing support for taxonomies in this issue.

**Comment by tomasbjerre** [comment]
Im putting this on my todo list. If you can supply an example, that qould be great

**Comment by tomasbjerre** [comment]
I am releasing this now. Open issue again if any problems!
