### ISSUE TITLE
SARIF 2.1.0 messages with placeholders

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [tomasbjerre/violations-lib#158]
[SarifParser](https://github.com/tomasbjerre/violations-lib/blob/8160e8a5062dc8bd529e8a2f38c478907d106577/src/main/java/se/bjurr/violations/lib/parsers/SarifParser.java) ignores the `message.arguments` property ([[SARIF-v2.1.0] §3.11.11](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317472)). It should locate the placeholders in the message string ([[SARIF-v2.1.0] §3.11.5](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317466)) and replace them with those arguments, and decode any `{{` or `}}` pairs that represent curly braces outside of placeholders.

Please see <https://github.com/tomasbjerre/violations-lib/issues/157#issue-1316576820> for a sample log with placeholders and arguments.

**Comment by tomasbjerre** [comment]
I think this is implemented now.
