### ISSUE TITLE
I am unable to parse a report

### ISSUE THREAD

**Issue by WoodyAsterisk** [tomasbjerre/violations-lib#166]
I am unable to parse a report:

npx violations-command-line -s INFO -mv 0 -v "PMD" "." ".*pmd/main\.xml$" "PMD" 
INFO Found 0 reports in . with pattern .*pmd(?:/|\\)main\.xml$

I didn't get any violations but I know there are a lot of them. I integrated correctly with Bitbucket but that line still appears. I tried some of your examples too.

INFO Found 0 reports in . with pattern .*pmd(?:/|\\)main\.xml$

**Comment by tomasbjerre** [comment]
Looks like there is no main.xml file in your path. What is the full path of the file containing the pmd violations?
