### ISSUE TITLE
Support golint

### ISSUE THREAD

**Issue by gruetter** [tomasbjerre/violations-lib#17]
Please support parsing the output of [golint](https://github.com/golang/lint).

**Comment by tomasbjerre** [comment]
Do you have a sample output?

Den 17 feb. 2017 14:47 skrev "Georg Grütter" <notifications@github.com>:

**Comment by gruetter** [comment]
Here a line (obfuscated a bit): 

> src/bla/bla/bla/dataSource.go:28:1: comment on exported type RestDataSource should be of the form "RestDataSource ..." (with optional leading article)

**Comment by gruetter** [comment]
It turns out that CPPLINT checker works fine for golint files (we tried CPPCHECK before).

**Comment by tomasbjerre** [comment]
I added a GoLint parser now. It also supports GoVet.

**Comment by gruetter** [comment]
Superb. Thanks a bunch, @tomasbjerre !
