### ISSUE TITLE
JUnit Message contains the whole stacktrace

### ISSUE THREAD

**Issue by oers** [tomasbjerre/violations-lib#173]
I am using the jenkins violation to gitlab plugin.
I noticed that violation.message contains the message as a combination of the failure message and the whole content. In may case that is the complete stacktrace of the assertion.

I found no way to limit the output of  {{{violation.message}}} to one line (which would be enough in my case)

Would it be possible to just put the <failure message="XXX"> into violation.message and the rest into specifics?

**Comment by tomasbjerre** [comment]
This can be fixed by switching Mustache to [Handlebars](https://github.com/jknack/handlebars.java), here:
https://github.com/tomasbjerre/violation-comments-lib/blob/master/src/main/java/se/bjurr/violations/comments/lib/ViolationRenderer.java

And a user of the tool can use a Handlebars helper to substring the message.

**Comment by oers** [comment]
Can i do this via coniguration? Or would I need to "compile" my own version of the plugin?

**Comment by tomasbjerre** [comment]
I implemented this here now:
https://github.com/tomasbjerre/violation-comments-lib

Hopefully one of the StringHelpers will solve your issue:
https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java

What tool do you use? I would prefer releasing only that tool to begin with. And have it battle tested before releasing all other tools.

**Comment by oers** [comment]
I am using the Jenkins Violations to Gitlab Plugin.

**Comment by tomasbjerre** [comment]
Releasing it now as 2.58. Open issue again if not working.

**Comment by oers** [comment]
Thx. I will test it after my holiday.
