### ISSUE TITLE
Add new Parser to support OWASP Dependency Check files 

### ISSUE THREAD

**Issue by DavidHaasz** [tomasbjerre/violations-lib#177]
Would it be possible to add in support for the OWASP Dependency Check report format that is produced when using the [Dependency Check Plugin](https://github.com/jeremylong/DependencyCheck)

The XSD for the XML Report format is available [here ](https://jeremylong.github.io/DependencyCheck/dependency-check.2.3.xsd)

**Comment by tomasbjerre** [comment]
This is same as https://github.com/tomasbjerre/violations-lib/issues/172 right?

**Comment by DavidHaasz** [comment]
I will give that a parser a test and will respond with the result

**Comment by DavidHaasz** [comment]
So attempting to parse an OWASP dependency check report using the SARIF parser failed with both XML and JSON OWASP Report formats. I did compare the JSON output of OWASP to the Sarif schema in src/main/resources/json/sarif-schema.json using an online validator and received the following errors:

Message:
Property 'reportSchema' has not been defined and the schema does not allow additional properties.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/additionalProperties

Message:
Property 'scanInfo' has not been defined and the schema does not allow additional properties.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/additionalProperties

Message:
Property 'projectInfo' has not been defined and the schema does not allow additional properties.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/additionalProperties

Message:
Property 'dependencies' has not been defined and the schema does not allow additional properties.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/additionalProperties

Message:
Required properties are missing from object: version, runs.
Schema path:
https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json#/required

so I think the format differs somewhat. For reference I was using version 8.2.1 of the OWASP Dependency Check maven plugin
