### ISSUE TITLE
Massive speed regression when processing lots of files

### ISSUE THREAD

**Issue by Daimanta** [tomasbjerre/violations-lib#179]
I work on a project that produces a long list of issues/bugs that we combine withe the gradle violations plugin. When upgrading to the newest version of the plugin we noticed a massive speed regression, turning the `violations` task runtime from 1 second to 6 minutes on a local pc or a CI timeout in our task runners. 

After some research we found that this was introduced in version 1.155.7 (we run 1.155.6 as a mitigation), specifically in ViolationUtils.java.

Our team determined that the following code in the culprit:

```
private static String getFileRelativeToCwd(final String cwd, final String file) {
    List<Path> allFound;
    try (final Stream<Path> stream = Files.walk(Paths.get(cwd))) {
      allFound =
          stream
              .filter(Files::isRegularFile)
              .filter((it) -> it.toFile().getAbsolutePath().endsWith(file))
              .collect(Collectors.toList());
    } catch (final IOException e) {
      allFound = new ArrayList<>();
    }
    if (allFound.isEmpty() || allFound.size() > 1) {
      return file;
    }
    return allFound.get(0).toFile().getAbsolutePath();
  }
```

This walks over the cwd every time a relative file path needs to be found. If the number of files is big on any side, this process can take a significant amount of time. With 1000 violations(in our project), you get 1000 walks over the contents of the cwd.

#### Possible solutions

This speed regression really kills the usability of this plugin when the amount of errors is big so I'd ask for a more performant solution.

Option 1:
Check if the old code can be used as this worked (in our case at the very least) and the code has no performance issues
Option 2:
If the tree walk is absolutely necessary, cache the result of the tree walk of 'cwd' and the iterate of the list of retrieved filename strings

**Comment by tomasbjerre** [comment]
Thanks for reporting, releasing a fix for this now as `1.156.5`. Open issue again if not working.
