### ISSUE TITLE
CodeClimate issue fingerprint clash

### ISSUE THREAD

**Issue by darekxan** [tomasbjerre/violations-lib#181]
I've noticed that in CodeClimate output converted from Android Lint's xml outputs several issues have the same fingerprint, despite being separate ones. I've tracked it down to fingerprint calculation, which already takes many properties to account:
https://github.com/tomasbjerre/violations-lib/blob/b4bb0214eb6f31ab2a80736cb285c733f285e98c/src/main/java/se/bjurr/violations/lib/model/codeclimate/CodeClimateTransformer.java#L59-L69
however this calculations skips the `endColumn`, `startLine` and  `endLine` properties.

I have encountered many lint issues that differ only by `startLine` or `endLine` properties.

To my understanding, according to [gitlab's CodeQuality specs](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool) `fingerprint` should be unique for each issue. 
This leads to several issues, despite being unique, having same fingerprint and being reported only once by gitlab code quality.

**Comment by tomasbjerre** [comment]
Im not currently using Gitlab so I dont really know. But this is intended, see:

- This issue: https://github.com/tomasbjerre/violations-maven-plugin/issues/1
- Fixed here: https://github.com/tomasbjerre/violations-lib/commit/1fff248fab4afe385e576a1cc475fb1f0f142db4

**Comment by tomasbjerre** [comment]
Releasing a fix for this by grouping same fingerprint using `other_locations`: https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#other-locations

Open issue again if not working.
