### ISSUE TITLE
Repeated message in the Coverity parser.

### ISSUE THREAD

**Issue by josejobin45** [tomasbjerre/violations-lib#188]
Hi,

I have been using the Coverity parser in the violations to the bitbucket plugin in Jenkins and it works as intended. But the message seems to be repeated. I believe it is due to this line: "https://github.com/tomasbjerre/violations-lib/blob/master/src%2Fmain%2Fjava%2Fse%2Fbjurr%2Fviolations%2Flib%2Fparsers%2FCoverityParser.java#L37" . Could you help ?

**Comment by tomasbjerre** [comment]
Can you supply:
- An example report
- Example string that is repeated
- Example of how you want it to look like

**Comment by josejobin45** [comment]
![PXL_20240402_120232546~2.jpg](https://github.com/tomasbjerre/violations-lib/assets/72434179/9e02ffa4-52c9-4571-99cc-f183101d3ab4)

As you can see in the highlighted part the message is getting repeated.

**Comment by josejobin45** [comment]
![PXL_20240402_120232546~2.jpg](https://github.com/tomasbjerre/violations-lib/assets/72434179/9e02ffa4-52c9-4571-99cc-f183101d3ab4)

As you can see in the highlighted part the message is getting repeated. 

![Screenshot_20240402-164806.png](https://github.com/tomasbjerre/violations-lib/assets/72434179/d7090aa6-236d-44f6-957e-9ba160ec1226)

I believe it is due to this

**Comment by tomasbjerre** [comment]
Released a fix now. Open issue again if not working.
