### ISSUE TITLE
No support of originalUriBaseIds and uriBaseId from sarif files

### ISSUE THREAD

**Issue by guilcy** [tomasbjerre/violations-lib#189]
Sarif files are defining 2 tag uriBaseId and originalUriBaseIds  to precise file path to access it.
File path = originalUriBaseIds[uriBaseId].uri + / + location.uri

uriBaseId is provided for each file location.

It seems the violation-libs does not allow take into consideration that hability resulting in wrong path name beeing used.
Base uri are defined that way:
  "originalUriBaseIds": {
        "SRCROOT0":

{           "uri": "file:///C:/Jenkins/workspace/_Module_PCS18Z_SmartReceivers_io/CODE/SOURCE/"         }
      },

Used and referenced by such tag:
{
          "location": {
              "uri": "Application/Classes/ControlPanel/ControlPanel/ControlPanelListener/ControlPanelListener.c",
              "uriBaseId": "SRCROOT0"
         }
,
          "mimeType": "text/x-c",
          "hashes":

{             "LOOKUP3-FILENAME+CONTENT": "6cf7a47a86aadbe3"           }

        }

The result file shoul be accessed at: file:///C:/Jenkins/workspace/_Module_PCS18Z_SmartReceivers_io/CODE/SOURCE/Application/Classes/ControlPanel/ControlPanel/ControlPanelListener/ControlPanelListener.c

I report the problem first into jenkins plugin at [JENKINS-73449](https://issues.jenkins.io/browse/JENKINS-73449).
The maintainer claimed that the feature/bug is missing from the violation-libs it is using.

**Comment by tomasbjerre** [comment]
Released a fix for this in `1.157.2`. Open issue again if any problems.
