### ISSUE TITLE
Support Facebook Infer

### ISSUE THREAD

**Issue by winterDroid** [tomasbjerre/violations-lib#20]
It would be great to support Facebook Infer: http://fbinfer.com/ It generates a bugs.txt, report.csv and report.json. Here you can find the files generated from the example Android project:
[bugs.txt](https://github.com/tomasbjerre/violations-lib/files/1095202/bugs.txt)
[report.csv](https://github.com/tomasbjerre/violations-lib/files/1095203/report_csv.txt)
[report.json](https://github.com/tomasbjerre/violations-lib/files/1095204/report_json.txt)

**Comment by tomasbjerre** [comment]
You can generate reports in PMD format according to this issue:
https://github.com/facebook/infer/issues/674

**Comment by winterDroid** [comment]
Nice thanks! Good to know!
