### ISSUE TITLE
Checkstyle: don't fail if rule attribute is not present

### ISSUE THREAD

**Issue by hectorj** [tomasbjerre/violations-lib#23]
Hi!

I'm having an issue with parsing checkstyle files coming from [phpstan](https://github.com/phpstan/phpstan) using this lib, as their errors don't have the `source` attribute, which makes this lib log an error and ignore the violation.

Would it be possible to consider the source as optional?

I am also opening an issue on phpstan to add the source attribute, as I am not sure which fix would be better.

**Comment by hectorj** [comment]
phpstan issue for reference : https://github.com/phpstan/phpstan/issues/481

**Comment by tomasbjerre** [comment]
Yes no problem. I'm releasing it now, will release the plugins later today.

**Comment by hectorj** [comment]
Thanks a lot!
