### ISSUE TITLE
URL Support for Violations

### ISSUE THREAD

**Issue by thenickfish** [tomasbjerre/violations-lib#25]
Resharper includes a WikiUrl attribute on some IssueTypes, as seen in the Resharper test xml file:
https://github.com/tomasbjerre/violations-lib/blob/master/src/test/resources/resharper/main.xml#L12

I am a user of your Violations to Bitbucket Server plugin, and was wondering if you would be interested in adding support for a URL in the comment, if the report file includes one, otherwise comment as-is. Maybe something like this for Resharper's case:
![image](https://user-images.githubusercontent.com/6274282/31349854-1fc2f37a-ace2-11e7-8ed0-abfb962a117a.png)

If you're interested in this as an enhancement I could do some work on it, probably starting by adding this to the Violation model. Will likely need some code review, as I'm not a Java dev, but I don't get offended. :)

Thanks again!

**Comment by tomasbjerre** [comment]
Yes looks like valuable information!

Perhaps it can be added as a part of to the `message` string? https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/parsers/ResharperParser.java#L42 It should just be a matter of adding the URL as it is and Bitbucket will render it as a link.

**Comment by thenickfish** [comment]
If this is only beneficial for Resharper, that's a perfect place for it! I'll take a look at it and submit a PR next time I have a free moment.

**Comment by thenickfish** [comment]
Thank you Tomas!
