### ISSUE TITLE
Single quotes in xml are printed as &apos; 

### ISSUE THREAD

**Issue by sjudd** [tomasbjerre/violations-lib#28]
I should have filed https://github.com/tomasbjerre/violations-gradle-plugin/issues/4 here since it looks like the issue is in the library not the plugin, here's a copy/paste of the original issue:

```
╠════════════╪═════════════════════════════════════════════════════════════════╪══════════╪══════╪═════════════════════════════════════════════════════════════════════╣
  ║ Checkstyle │ com.puppycrawl.tools.checkstyle.checks.imports.ImportOrderCheck │ ERROR    │ 6    │ Wrong order for &apos;android.content.ContentResolver&apos; import. ║
  ╚════════════╧═════════════════════════════════════════════════════════════════╧══════════╧══════╧═════════════════════════════════════════════════════════════════════╝
```

It's probably possible to render them as expected, if nothing else by just replacing the few special characters xml seems to allow: http://xml.silmaril.ie/specials.html.

**Comment by sjudd** [comment]
I looked in to guava and it has only escapers, not unescapers so it doesn't seem like it will resolve this. The apache commons library looks like it has unescapers, though a bunch of them are deprecated.

It looks like it's actually pretty easy to just write an unescaper myself, so that's the approach I've taken for now. If you'd rather depend on apache commons or think it's worth spending more time looking for some common library to depend on, I'm happy to do so as well. 

PR will be up shortly.

**Comment by tomasbjerre** [comment]
This is released now!
