### ISSUE TITLE
Add support for NullAway

### ISSUE THREAD

**Issue by leinardi** [tomasbjerre/violations-lib#33]
It would be nice to have support for the Error Prone's plugin [NullAway](https://github.com/uber/NullAway). It is getting really popular and is quite useful to help eliminate `NullPointerException`.

The console output looks like this:
```
:sample:compileReleaseNdk NO-SOURCE
:sample:processReleaseJavaRes NO-SOURCE
/home/travis/build/leinardi/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialActionItem.java:162: error: [NullAway] initializer method does not guarantee @NonNull field mLabel is initialized along all control-flow paths (remember to check for exceptions or early returns).
        public Builder(@IdRes int id, @DrawableRes int fabImageResource) {
               ^
    (see http://t.uber.com/nullaway )
/home/travis/build/leinardi/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialActionItem.java:175: error: [NullAway] initializer method does not guarantee @NonNull field mLabel is initialized along all control-flow paths (remember to check for exceptions or early returns).
        public Builder(@IdRes int id, @Nullable Drawable drawable) {
               ^
    (see http://t.uber.com/nullaway )
2 errors
```

My guess is that shouldn't be too different to parse than the base Error Prone error.

**Comment by tomasbjerre** [comment]
I added that output and tried with the Error Prone parser and I think it looks good. Did you try that?

**Comment by leinardi** [comment]
You are right, this is working, I guess the report were missing because I got the errors on old code and I have `commentOnlyChangedContent` set to `true`.

Thanks again for the nice plugin :+1: 

PS
Any chance you can have a look at #34
