### ISSUE TITLE
Incomplete rule IDs in Flake8 parser

### ISSUE THREAD

**Issue by IvanAnishchuk** [tomasbjerre/violations-lib#46]
Flake8 parser only reports numerical part of rule ids (e.g. PyLint correctly reports all letters and digits and even rule names as it should). Example:

```
Reporter: Flake8
Rule: 265
Severity: ERROR
File: src/aim/init.py L5
block comment should start with '# '

Reporter: Flake8
Rule: 302
Severity: ERROR
File: src/aim/init.py L6
expected 2 blank lines, found 0
```

```
src/aim/__init__.py:5:1: E265 block comment should start with '# '
src/aim/__init__.py:6:1: E302 expected 2 blank lines, found 0
```

As you can see `E265` becomes just `265`. Those leading letters are sometimes extremely relevant (they are usually different for different tools flake8 wraps). Can someone please fix it or at least point me to where I should look (though I'm not very experienced with java this is probably simple enough).

**Comment by IvanAnishchuk** [comment]
I suspect one could simply tweak the regexp [here](https://github.com/tomasbjerre/violations-lib/blob/df5387dbf1d4db3afc6882e49dd8e582394b3207/src/main/java/se/bjurr/violations/lib/parsers/Flake8Parser.java#L29) but, again, I'd rather have some direction because this lib is new to me and I don't wanna break something.

**Comment by tomasbjerre** [comment]
Released now. Open issue again if not working!
