### ISSUE TITLE
Change in output for Gradle 5.0 (KotlinGradleParser)

### ISSUE THREAD

**Issue by scott-kennedy-ck** [tomasbjerre/violations-lib#47]
I've been testing out Gradle 5.0-rc-1, and KotlinGradleParser is no longer working.  The output has changed to this format:

`utils/src/main/kotlin/com/somepackage/WebView.kt:38:9: warning: 'setter for pluginState: WebSettings.PluginState!' is deprecated. Deprecated in Java`

I don't know if it's worth supporting this before Gradle 5.0 is released, but I'll leave this here as a todo.

**Comment by tomasbjerre** [comment]
Looks like this: https://github.com/tomasbjerre/violations-lib/blob/master/src/test/resources/gcc/output.txt

You may try the `CLANG` parser.

**Comment by scott-kennedy-ck** [comment]
Seems that updating all my dependencies to stable versions has resolved this.  Thanks.
