### ISSUE TITLE
Ability to parse violations based on a regex

### ISSUE THREAD

**Issue by oyvindlr** [tomasbjerre/violations-lib#49]
I would like to be able to parse the output from my own homemade tool. Instead of adding a new parser to the library, the easiest thing would be if there was support for generic regex parsing. This is for example possible in the Jenkins warnings plugin.

What complicates things is that the regex parser requires a parameter, so it can't use the same interface as the other parsers. I have a suggestion for how to do this, but I'm not sure of it. I'll create a pull request.

**Comment by tomasbjerre** [comment]
Perhaps possible by letting that parser read properties?

But I would like to see the actual use case. Are you not able to produce a format like any of the ones that are supported? https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources

And if not, why?

**Comment by oyvindlr** [comment]
You're right, I should be able to put this into an existing format. 
The use case is that I have a tool which will parse the code for certain violation-suppression comments and some other tags. Whenever a new such tag is added, it needs to be approved by someone authorized. I would like for the comments-to-stash plugin to create a task in the pull request for each new tag.

**Comment by oyvindlr** [comment]
So it's probably not necessary, but please have a look at this branch:
https://github.com/oyvindlr/violations-lib/tree/generic-regex-parser-%2349

**Comment by tomasbjerre** [comment]
I added some random comments there =)

**Comment by oyvindlr** [comment]
What exactly do you mean by "reading properties"?

**Comment by tomasbjerre** [comment]
In `RegexParser` do a `System.getProperties().get("se.bjurr.violations.lib.parsers.regexparser.regexp",null)` that should contain a valid regexp according to the validation that you have implemented in `containsAllMandatoryGroups`.

**Comment by oyvindlr** [comment]
Ok, but how would an application using the library know that this property must be set? The idea was that the application could check if the parser is of the ViolationsParserWithParameters  class, and, if so, add text input fields for all parameters and use the provided description for user help. 
I know it's overkill if this is the only parser that uses it :)

**Comment by tomasbjerre** [comment]
You are right. I'll have to think about this for a while. To me, it is very important to keep it simple and reduce maintenance time. It is my experience that people are more enthusiastic about adding features than spending time helping maintaining them =)

But if we take a step back. You said "_I should be able to put this into an existing format._" so this change is not really needed right? And without a use case I think it should not be added.

**Comment by oyvindlr** [comment]
Yes, for now I can probably re-work my tool instead. Perhaps this kind of feature would be better to work into the specific application, instead of having one parser being treated differently.

**Comment by davidhart82** [comment]
This is exactly what I was looking for today! I didn't want to go through the effort of putting a pull request to support the output of protolint, and this would have fit the bill perfectly!

**Comment by tomasbjerre** [comment]
Open an issue about protolint and supply some sample report.

**Comment by davidhart82** [comment]
I'm just about to submit the PR...
