### ISSUE TITLE
puppet-lint

### ISSUE THREAD

**Issue by FallibleFlyer** [tomasbjerre/violations-lib#50]
If you are asking for support of a new format, or if you are unable to parse a report:
http://puppet-lint.com/
Some samples on site.

Please provide example output of such a report.
ERROR: two-space soft tabs not used on line 181
ERROR: two-space soft tabs not used on line 182
ERROR: two-space soft tabs not used on line 183
ERROR: two-space soft tabs not used on line 184
ERROR: two-space soft tabs not used on line 185
WARNING: indentation of => is not properly aligned (expected in column 26, but found it in column 16) on line 40
WARNING: indentation of => is not properly aligned (expected in column 26, but found it in column 16) on line 62
WARNING: indentation of => is not properly aligned (expected in column 26, but found it in column 16) on line 84
WARNING: indentation of => is not properly aligned (expected in column 26, but found it in column 16) on line 106
WARNING: indentation of => is not properly aligned (expected in column 26, but found it in column 16) on line 128

**Comment by tomasbjerre** [comment]
I think the `CLANG` parser should work, if you specify a format like this:

`-log-format %{fullpath}:%{line}:%{column}: %{kind}: %{message}`

Does that work for you?

Perhaps you also need to add %{filename} to get the path and filename right. See the docs:
```
        --log-format FORMAT          Change the log format.
                                     Overrides --with-filename.
                                     The following placeholders can be used:
                                     %{filename} - Filename without path.
                                     %{path}     - Path as provided to puppet-lint.
                                     %{fullpath} - Expanded path to the file.
                                     %{line}     - Line number.
                                     %{column}   - Column number.
                                     %{kind}     - The kind of message (warning, error).
                                     %{KIND}     - Uppercase version of %{kind}.
                                     %{check}    - The name of the check.
                                     %{message}  - The message.
```

**Comment by FallibleFlyer** [comment]
That works just fine! Thanks for the point in the right direction.

Unrelated, the readme/docs are incorrect for pipelines. The credential fields were changed to just be credentialID
