### ISSUE TITLE
Embedded Ruby Templates

### ISSUE THREAD

**Issue by FallibleFlyer** [tomasbjerre/violations-lib#51]
If you are asking for support of a new format, or if you are unable to parse a report:
https://www.puppetcookbook.com/posts/erb-template-validation.html

Please provide example output of such a report.
-:79: unknown regexp options - appl
-:79: syntax error, unexpected '<'
...WLTempDir /var/appl/logs/dir/<%= scope['scope_sites::...
...                               ^
-:91: syntax error, unexpected keyword_do_block, expecting ')'
...:wlproxy_inxe_ms'].sort.each do |priority, hosts|
...                               ^
-:91: syntax error, unexpected '|', expecting '='
-:92: syntax error, unexpected keyword_do_block, expecting ')'
hosts.sort.each do |i|
                  ^
-:94: syntax error, unexpected keyword_end, expecting ')'
-:349: syntax error, unexpected keyword_do_block, expecting end-of-input
...::static_content_dirs'].each do |path|
...

**Comment by tomasbjerre** [comment]
The format has to contain filenames.

Perhaps you can make it output one of the already implemented formats: https://github.com/tomasbjerre/violations-lib/tree/master/src/test/resources

**Comment by FallibleFlyer** [comment]
I was able to force it into a readable format with some persuasion.
erb -P -x -T '-' \"${it}\" | ruby -c 2>&1 >/dev/null | grep '^-' | sed -E 's/^-([a-zA-Z0-9:]+)/${filename}\\1 ERROR:/p' > erbfiles.out
