### ISSUE TITLE
Shouldn't CodeNarc-Parsing respect SourceDirectory-Element

### ISSUE THREAD

**Issue by foto-andreas** [tomasbjerre/violations-lib#53]
On the CodeNarc Website there is an example file [CodeNarc-Example](http://codenarc.sourceforge.net/SampleCodeNarcXmlReport.xml) which includes the Element "SourceDirectory", which is filled by CodeNarc. The "path" attribute is not filled. The current implementation of CodeNarcParser here respects only the path-attribute but ignores the "SourceDirectory". In our multi project builds using gradle this results in source files not being found.

I would suggest to prepend the path + name with the text-content of SourceDirectory.

**Comment by tomasbjerre** [comment]
Seems to be some problems with Maven Central and Bintray right now but I'll release it soon.

**Comment by tomasbjerre** [comment]
released now

**Comment by foto-andreas** [comment]
problem: the slash after project should only be added if project is not empty

**Comment by tomasbjerre** [comment]
Should be fixed now.
