### ISSUE TITLE
locationChunks in CppCheck are reported as individual violations

### ISSUE THREAD

**Issue by uhafner** [tomasbjerre/violations-lib#54]
I'm using your CppCheck parser in Jenkins Warnings plugin to read cppcheck files. In your parser you are converting each "location" of the original error structure to a violation. Actually each error should be converted to *one* violation only. Your violations should also provide a concept of multiple locations per violation (see SonarQube or [Warning Plugin](https://github.com/jenkinsci/analysis-model/blob/master/src/main/java/edu/hm/hafner/analysis/Issue.java#L524) for an example).

See original [Jenkins bug report](https://issues.jenkins-ci.org/browse/JENKINS-55733).

**Comment by uhafner** [comment]
See discussion in https://issues.jenkins-ci.org/browse/JENKINS-55733.

**Comment by uhafner** [comment]
The discussion in the Jenkins issue seems to indicate, that each toplevel warning in the issue is the thing that should be counted.

**Comment by uhafner** [comment]
Do you think this is feasible? This will require changes in the API.

**Comment by tomasbjerre** [comment]
This library finds the `id` of each error and uses that as "rule" which is available on each `Violation`. Which means you can transform the list from the lib to a map of with one list per error. Does this help?
```
    final List<Violation> violationsList =
        violationsApi() //
            .withPattern(".*/cppcheck/example1\\.xml$") //
            .inFolder(rootFolder) //
            .findAll(CPPCHECK) //
            .violations();

    final Map<String, List<Violation>> violationsPerRule =
        violationsList
            .stream() //
            .collect(Collectors.groupingBy(Violation::getRule));
    assertThat(violationsPerRule) //
        .hasSize(2);
    assertThat(violationsPerRule.get("redundantAssignment")) //
        .hasSize(2);
```

**Comment by uhafner** [comment]
I think that will work. Thanks for the help!

**Comment by uhafner** [comment]
After thinking (or coding) it a little bit further I think that it does not work this way. The problem is that we can have multiple error tags using the same `id` (actually a bad name, `id` means rule id, it is not unique in the error tag).

**Comment by tomasbjerre** [comment]
Perhaps a `group` attribute can solve this?

```
    final List<Violation> violationsList =
        violationsApi() //
            .withPattern(".*/cppcheck/example1\\.xml$") //
            .inFolder(rootFolder) //
            .findAll(CPPCHECK) //
            .violations();

    final Map<String, List<Violation>> violationsPerGroupMap =
        violationsList
            .stream() //
            .collect(Collectors.groupingBy(Violation::getGroup));
    assertThat(violationsPerGroupMap) //
        .as("There are 2 error tags and there should be 2 groups identified.") //
        .hasSize(2);
```

So that in this example `violationsPerGroupMap` is a map with a `key` for each `error` tag and a `value` with a list of all `location` tags within that `error` tag.

**Comment by uhafner** [comment]
Ok, that should work now 👍

**Comment by uhafner** [comment]
Verified in https://github.com/jenkinsci/analysis-model/commit/5e28d1b247abdefe972823c9ed83f687785c99c3.
