### ISSUE TITLE
Support for IAR compiler warnings

### ISSUE THREAD

**Issue by stoesselt** [tomasbjerre/violations-lib#55]
With cmdline option '--no_wrap_diagnostics' the reported problems are provided in a single line. Output is like following:

> "c:\jenkins\workspace\24-Test-Jenkins-WinTen-Extension\external\specific\cpp\iar_cxxabi.cpp",432  Warning[Pe852]: expression must be a pointer to a complete object type

Instead of a warning, the following can occur as well:  Error|Remark|Warning|Fatal [Ee]rror

As I remember, the Violations to Bitbucket Server plugin needs relative parts to repo root, something like this needs to be recognized (as well):

> "external\specific\cpp\iar_cxxabi.cpp",432  Warning[Pe852]: expression must be a pointer to a complete object type

IAR compiler only works on Windows. I would also go with a solution where backslash has to be replaced by slash.

**Comment by tomasbjerre** [comment]
I'm not familiar with this but I found this:
http://www.keil.com/support/man/docs/armcc/armcc_chr1359124913823.htm
And I suspect that `--diag_style=gnu` may result in a format that is equivalent to:
https://github.com/tomasbjerre/violations-lib/blob/master/src/test/resources/arm-gcc/output.txt
And parsable with `CLANG` that is already implemented.

Can you verify that? If so I'd like to add it to the `README.md`.

**Comment by stoesselt** [comment]
The Keil compiler is not the same as IAR compiler. So I cannot confirm, that the Keil compiler does what the compiler options says.

Nonetheless I had a look and searched for comparabile compiler options for IAR compiler, but without luck. However, the manual states that the output is always formated like:
> filename,linenumber level[tag]: message
Where level could be one of Error|Remark|Warning|Fatal [Ee]rror

**Comment by stoesselt** [comment]
Just as reference for the IAR compiler manual: http://ftp.iar.se/WWWfiles/arm/webic/doc/EWARM_DevelopmentGuide.ENU.pdf

**Comment by tomasbjerre** [comment]
Ok! Then perhaps this parser can be named `IARParser`.

**Comment by tomasbjerre** [comment]
Released 1.97 of the Bitbucket Server plugin now with this parser.
