### ISSUE TITLE
Support for Microsoft Visual C++ compiler via msys2 makefile

### ISSUE THREAD

**Issue by stoesselt** [tomasbjerre/violations-lib#56]
Output is like the following:

> ../../source/gui/controls/DebugPrint.cpp(30): warning C4311: "Typumwandlung": Zeigerverkrzung von "void *" zu "long"

Relative to repo root it would be

> source/gui/controls/DebugPrint.cpp(30): warning C4311: "Typumwandlung": Zeigerverkrzung von "void *" zu "long"

My proposal:

`(.*)\((\d+)\):  (warning.*)`
`(.*)\((\d+)\): ((?:fatal |)error.*)`

**Comment by tomasbjerre** [comment]
I'm trying to find the actual tool that outputs this information. Is it MSYS2 or is the Makefile invoking some other tool to produce this output?

**Comment by stoesselt** [comment]
So I am using a GNU makefile for build process. The actual compiler is the Microsoft C++ Compiler. And the output, in case of a warning or error, is not further manipulated, so the lines given above are directly from compiler.

In first shot I was unsure, whether the Makefile has anything to do with the output, but in case of a warning, it is not.

**Comment by tomasbjerre** [comment]
Ok! Then this parser can perhaps be named something like `MSCPP`.

**Comment by tomasbjerre** [comment]
This is not same as `msbuild` output right?

**Comment by stoesselt** [comment]
If I understand it correctly, msbuild is something above the compiler (cl.exe) and linker (link.exe). The output, I provided in this issue, is retrieved directly from calling cl and link.

I was wondering about the MSBuild parser provided here (https://github.com/jenkinsci/analysis-model), used for the Warnings Next Generation Plugin. It recognizes the warning. Some currently I would say it is the same as msbuild output.

**Comment by tomasbjerre** [comment]
Might be this line picking it up:
https://github.com/jenkinsci/analysis-model/blob/c18da84f8ca080542c7245af6353700f681e66a1/src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java#L25

But I think it is better to have different parsers for different formats. Looks like that MsBuildParser can parse 5 different formats. So I think I want this in an `MSCPPParser`.

**Comment by stoesselt** [comment]
For me, this looks like a very compilcated regex. I don't know which performance optimizations it has (if any), but from my point of view my proposal from the first post in this issue is more maintainable.

**Comment by tomasbjerre** [comment]
I have a working parser: https://github.com/tomasbjerre/violations-lib/blob/feature/mscpp-iar/src/main/java/se/bjurr/violations/lib/parsers/MSCPPParser.java

But would really need some more output to use for testing!

**Comment by stoesselt** [comment]
Great, tomorrow I can provide some more output.

**Comment by tomasbjerre** [comment]
Great! Would also be good if you can get some mor IAR output.

**Comment by stoesselt** [comment]
> ../dummies/osal/own_os/threading/Mutex.cpp(14): error C2065: "foobar": nichtdeklarierter Bezeichner
> ../dummies/osal/own_os/threading/Mutex.cpp(15): error C2143: Syntaxfehler: Es fehlt ";" vor "}"
>../../source/gui/controls/Keyboard/AlphabetKeyboard.cpp(157): warning C4267: "=": Konvertierung von "size_t" nach "PEGSHORT", Datenverlust m”glich

**Comment by tomasbjerre** [comment]
Released 1.97 of the Bitbucket Server plugin now with this parser.
