### ISSUE TITLE
Read from a String, instead of a file pattern

### ISSUE THREAD

**Issue by henriquetruta** [tomasbjerre/violations-lib#59]
It'd be nice if instead of providing a folder and a pattern, I could just use a String. Something like:

```
String content = "foo report"
 violationsApi()
          .withContent(content)
          .findAll(CHECKSTYLE)
          .violations();
```

**Comment by tomasbjerre** [comment]
Does the file contain only checkstyle?

If so. You can use the parser directly. 
Parser.CHECKSTYLE.parseReportOutput(content)

https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/parsers/CheckStyleParser.java

**Comment by henriquetruta** [comment]
That did the trick! Thanks!
It's probavly good to have a case like this on the README. 
Thanks again

**Comment by tomasbjerre** [comment]
Nice!
