### ISSUE TITLE
Sonar Parser : Wrong Severity level -> when unknow then by default set to INFO

### ISSUE THREAD

**Issue by didos36** [tomasbjerre/violations-lib#67]
Hello,

I'm currently trying to integrate Sonar report parser.
Unfortunatly when issue level is not marchy Severity enum then its fallback to INFO, which is not very usefull when I want to only report the equivalent of WARN level.
From Sonar documentation, here are the existing levels are blocker, critical, major, minor, info.
Is it possible to convert level between Sonar -> violation lib?
If the assumption is to stay with the same existing levels, my proposal would be:
info, minor => INFO
major, critical => WARN
blocker => ERROR

**Comment by tomasbjerre** [comment]
Released now. Like your proposal.

**Comment by didos36** [comment]
Thanks!
