### ISSUE TITLE
Findbugs parser misses bugs

### ISSUE THREAD

**Issue by magnayn** [tomasbjerre/violations-lib#7]
Line 51 does:
`List<String> sourceLineChunks = getChunks(bugInstanceChunk, "<SourceLine", "/>");
`
This does not match the following valid xml
`<SourceLine classname='com.mycompany.app.App' start='7' end='30' sourcepath='com/mycompany/app/App.java' sourcefile='App.java'><Message>At App.java:[lines 7-30]</Message></SourceLine>
`
I'd imagine an XML Pull Parser may be an easier way to extract this sort of stuff..

**Comment by tomasbjerre** [comment]
Tanks for this one! I will release it in the plugins now.
