### ISSUE TITLE
Still comment on unchanged lines if "Comment only changed part of files" is checked

### ISSUE THREAD

**Issue by shyingsheng** [tomasbjerre/violations-lib#72]
Hello,

Still found violation on unchanged lines as I have checked on the option "Comment only changed part of files"

See below comments from Gitlab Merge request, which reported the ERROR on L243.
Found 1 violations:

**Reporter**: CPPLint **Rule**: whitespace/parens  
 **File**: src/imageview/setting/image_setting_dlg.cpp L243
 Missing space before ( in if(  
 **Severity**: *********_ERROR_*********

But as I checked the change diff from the Merge request, I found L243 was not changed at all. See below screenshot.
![image](https://user-images.githubusercontent.com/23226967/60573769-e98f6200-9daa-11e9-9e2c-ddce41675728.png)

Is it possible to explain why it happens? Is this the right behaviour or not? why?

Thank you very much.

**Comment by tomasbjerre** [comment]
Duplicate: https://github.com/jenkinsci/violation-comments-to-gitlab-plugin/issues/19
