### ISSUE TITLE
Support CodeClimate as output format for GitLab integration

### ISSUE THREAD

**Issue by terje2001** [tomasbjerre/violations-lib#76]
First off: Thanks for a great set of tools for integrating quality tools to Gitlab, etc!!

Second: How hard would it be to add CodeClimate JSON output as an optional goal?
Why: GitLab natively supports this json format for integrating 3rd party code quality tools. Please see https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool. Unless I am wrong, it would be _fantastic_ to have your plugin parse all known output formats as you do today and merge it to this format instead of the complexity of the codeclimate tools...

**Comment by tomasbjerre** [comment]
I added this feature in the command line tool: https://github.com/tomasbjerre/violations-command-line

Not really sure which ones of the tools it belongs in. Perhaps also these:
 * [Violations Maven Plugin](https://github.com/tomasbjerre/violations-maven-plugin).
 * [Violations Gradle Plugin](https://github.com/tomasbjerre/violations-gradle-plugin).

**Comment by tomasbjerre** [comment]
Open issue again if any problems.

**Comment by terje2001** [comment]
Tjena Tomas,

Absolutely fantastic, thank you so much for doing this and getting it released so fast!!!

I have included it in our CI/DI in Gitlab for the last week now, and it works really well. The only issue is that the file references are slightly of in the various reports so the individual items are not clickable (i.e. take one to the sorce file). No matter, this is a huge improvement to our process!
