### ISSUE TITLE
Add hadolint support

### ISSUE THREAD

**Issue by reitzmichnicht** [tomasbjerre/violations-lib#77]
Please provide support for Hadolint
https://github.com/hadolint/hadolint

This is the most popular linter for Dockerfiles.

Linting output is written to console:
```
Dockerfile:13 DL3018 Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
Dockerfile:16 DL4006 Set the SHELL option -o pipefail before RUN with a pipe in it
```

Kind regards,
Michael

**Comment by tomasbjerre** [comment]
Are you sure you cannot export to checkstyle already?https://github.com/hadolint/hadolint/blob/master/src/Hadolint/Lint.hs#L29

**Comment by reitzmichnicht** [comment]
Thanks for the hint, that feature was not documented.
