### ISSUE TITLE
CPPCheckParser does not parse auto closed <error/> tags

### ISSUE THREAD

**Issue by djpeinado** [tomasbjerre/violations-lib#82]
[CPPCheckParser.java](https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/parsers/CPPCheckParser.java)

`final List<String> errorChunks = getChunks(string, "<error", "</error>");`

This code does not parse <error/> tags.

When I run `cppcheck` with `--xml` parameter, the output I get is `<error/>` and not `<error></error>`

**Comment by djpeinado** [comment]
Sample cppcheck output:
`<?xml version="1.0" encoding="UTF-8"?>
<results>
    <error file="filename.cpp" line="49" id="variableScope" severity="style" msg="The scope of the variable &apos;softwareComponentsAreOk&apos; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &apos;i&apos; can be reduced:
void f(int x)
{
    int i = 0;
    if (x) {
        // it&apos;s safe to move &apos;int i = 0;&apos; here
        for (int n = 0; n &lt; 10; ++n) {
            // it is possible but not safe to move &apos;int i = 0;&apos; here
            do_something(&amp;i);
        }
    }
}
When you see this message it is always safe to reduce the variable scope 1 level."/>
</results>`

**Comment by tomasbjerre** [comment]
All the tools should have this fix now! Open issue again if not working.

**Comment by uhafner** [comment]
This fix caused a regression in the warnings plugin, it breaks one of my test cases: https://github.com/jenkinsci/analysis-model/pull/291

Seems that now some violations are reported twice: for the following file I get three violations per error now. With the previous release I got only two violations (and that seems to be correct).  
```
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
  <cppcheck version="1.52"/>
  <error id="redundantAssignment" severity="style" msg="Variable &apos;it&apos; is reassigned a value before the old one has been used." verbose="Variable &apos;it&apos; is reassigned a value before the old one has been used." cwe="563">
    <location file0="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" file="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" line="53"/>
    <location file0="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" file="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" line="51"/>
    <symbol>it</symbol>
  </error>
  <error id="redundantAssignment" severity="style" msg="Variable &apos;that&apos; is reassigned a value before the old one has been used." verbose="Variable &apos;that&apos; is reassigned a value before the old one has been used." cwe="563">
    <location file0="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" file="that\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" line="51"/>
    <location file0="apps\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" file="that\cloud_composer\src\point_selectors\rectangular_frustum_selector.cpp" line="53"/>
    <symbol>that</symbol>
  </error>
</results>
```

**Comment by tomasbjerre** [comment]
I added a test case, and I do get 4 violations:
https://github.com/tomasbjerre/violations-lib/commit/2b96ad75cee880a97c87fea81d027937db267640

**Comment by tomasbjerre** [comment]
@uhafner I add the result to a `Set` to get rid of duplicates:
https://github.com/tomasbjerre/violations-lib/blob/master/src/main/java/se/bjurr/violations/lib/reports/Parser.java#L108

 I think that is why you get 6 results, and I get 4.

**Comment by uhafner** [comment]
Ok, this was not required in 1.109. Nevertheless, since I am already storing all the issues in a set I can change that in my implementation quite easily (see https://github.com/jenkinsci/analysis-model/commit/8258926aff8d494e6686a8ce9cdaf131d46483cd). Thanks for the tip!
