### ISSUE TITLE
XUnit parser

### ISSUE THREAD

**Issue by HeidiRechek** [tomasbjerre/violations-lib#84]
npx violation-comments-to-bitbucket-cloud-command-line -username *** -password *** -ws *****  -rs jenkins_test  -prid 43  -v "JUNIT" "." ".*/reports/mocha-test-results.xml$" "Junit" -keep-old-comm
ents true
Feb 27, 2020 10:42:00 AM se.bjurr.violations.lib.parsers.JUnitParser parseReportOutput
WARNING: Found failure, but failed to find fail line from stacktrace

**Comment by tomasbjerre** [comment]
Can you attach the mocha-test-results.xml file?

**Comment by HeidiRechek** [comment]
[mocha-test-results.txt](https://github.com/tomasbjerre/violations-lib/files/4262833/mocha-test-results.txt)

**Comment by HeidiRechek** [comment]
Second example: 
 npx violation-comments-to-bitbucket-cloud-command-line -username **** -password **** -ws *****  -rs jenkins_test  -prid 43  -v "JUNIT" "." ".*/reports/stylelint-test-results.xml$" "Junit" -keep-old-
comments true
Feb 27, 2020 10:48:26 AM se.bjurr.violations.lib.reports.Parser findViolations
SEVERE: Error when parsing C:\Github\jenkins_test\org_****\.\reports\stylelint-test-results.xml as JUNIT
java.lang.RuntimeException: "classname" not found in "<testcase name="max-empty-lines">
      <failure type="error" message="Expected no more than 1 empty line (max-empty-lines)">On line 3, column 1 in C:\Github\jenkins_test\org_******\cartridges\org_******\cartridge\client\default\scss\homePage.scss</failure>
    </testcase>"
        at se.bjurr.violations.lib.util.ViolationParserUtils.getAttribute(ViolationParserUtils.java:72)
        at se.bjurr.violations.lib.parsers.JUnitParser.parseReportOutput(JUnitParser.java:32)
        at se.bjurr.violations.lib.reports.Parser.findViolations(Parser.java:115)
        at se.bjurr.violations.lib.ViolationsApi.violations(ViolationsApi.java:58)
        at se.bjurr.violations.main.Runner.main(Runner.java:185)
        at se.bjurr.violations.main.Main.main(Main.java:6)

[stylelint-test-results.txt](https://github.com/tomasbjerre/violations-lib/files/4262848/stylelint-test-results.txt)

**Comment by tomasbjerre** [comment]
Actually, XUnit is not implemented. But can be, I'll consider this a feature request.

Note to self:

 * https://xunit.net/docs/format-xml-v2
 * https://mochajs.org/#reporters

**Comment by tomasbjerre** [comment]
Releasing a `XUNIT` parser now. Open issue again if any problems.

**Comment by HeidiRechek** [comment]
I have updated and verified my local violation-comments-to-bitbucket-cloud-command-line is 1.16 but when I try command I get  Exception in thread "main" java.lang.IllegalArgumentException: No enum constant 

npx violation-comments-to-bitbucket-cloud-command-line -username ***** -password *****  -ws ******  -rs jenkins_test  -prid 45 
-v "CHECKSTYLE" "." ".*/reports/eslint-checks
tyle-results.xml$" "ESlint" 
-v "XUNIT" "." ".*/reports/mocha-test-results.xml$" "XUnit" 
-keep-old-comments true
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant se.bjurr.violations.lib.reports.Parser.XUNIT
        at java.lang.Enum.valueOf(Unknown Source)
        at se.bjurr.violations.lib.reports.Parser.valueOf(Parser.java:57)
        at se.bjurr.violations.main.Runner.main(Runner.java:181)
        at se.bjurr.violations.main.Main.main(Main.java:6)

**Comment by tomasbjerre** [comment]
"It works on my machine" =)

```
npx violation-comments-to-bitbucket-cloud-command-line \
 -cocf false -csfc false -cocc false -ccwasfc true -username tomasbjerre -password asdasdasd  -ws tomasbjerre -rs violations-test -prid 1 \
 -comment-template "

-----------

`{{changedFile.filename}}`


**{{violation.rule}}**


{{violation.message}}


 "\
 -v "XUNIT" "." ".*txt$" "XUnit"
```

And result:
https://bitbucket.org/tomasbjerre/violations-test/pull-requests/1/some-crap/diff

**Comment by HeidiRechek** [comment]
Does an xunit need to be  filename.txt instead of .xml?

**Comment by tomasbjerre** [comment]
No it can be any filename.

**Comment by HeidiRechek** [comment]
Are you able to use that command against my mocha-test-results from the ticket?

**Comment by tomasbjerre** [comment]
Yes
