### ISSUE TITLE
CppCheck parser errors out on translation unit with no warnings followed by self-closing XML tag

### ISSUE THREAD

**Issue by bracketttc** [tomasbjerre/violations-lib#86]
```
<errors>
</errors>
```
in clean `cppcheck` output causes an error about finding an `<error` tag lacking a `sensitivity` field.

Apologies for not including full error message and `cppcheck` output - posting from my phone.

**Comment by tomasbjerre** [comment]
I added a testcase. Cannot reproduce it.

**Comment by bracketttc** [comment]
Pulled the repo, replaced `empty.xml` with the actual full text of an empty `cppcheck` report and that doesn't error out either.

Need to log into my work network and check the Jenkins logs and artifacts again. Maybe there's some complicating factor that I'm missing -- or it could simply be that the error has been fixed in the most recent code and we're using an out-of-date library.

**Comment by bracketttc** [comment]
Slightly more complicated. When parsing a log file with multiple `cppcheck` reports, a clean `cppcheck` xml followed by any self-closing XML tag in the log will attempt to be parsed as an `<error>` tag and throw within `violations-lib`. That exception is caught, but any findings parsed are not preserved.
```
<errors>
</errors>
</results>
... Unrelated CMake output
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
<cppcheck version="1.86"/>
```
