### ISSUE TITLE
The project can't be built

### ISSUE THREAD

**Issue by remal** [tomasbjerre/violations-lib#88]
I'm trying to send a PR and unfortunately can't build the project.

I'm using IDEA and it configures the project based on Gradle script. IDEA configured JDK 1.8 for the project.

When I'm trying to execute `build` task, I'm getting this error:
```
Execution failed for task ':googleJavaFormat'.
> com/google/googlejavaformat/java/JavaFormatterOptions$Style has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Please find full stacktrace [here](https://github.com/tomasbjerre/violations-lib/files/4761034/stacktrace.txt).

Could you please explain what I'm doing wrong?

**Comment by remal** [comment]
> Can you build it from command line? ./gradlew build

I tried and it didn't help.

 

Looks like Google Java Format tool that is used from Gradle build in the project is compiled for Java 11. Could you tell me what JDK version you're using?

**Comment by remal** [comment]
Tried JDK 11. It works. If I'm right with the assumption that JDK 11 should be used, the issue can be closed. And... Could you please reflect it somewhere (i.e. `CONTRIBUTING.md`)?

**Comment by tomasbjerre** [comment]
No 8 should be used. I guess this issue might be caused by a new release of google-java-format-gradle-plugin: https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/java.gradle#L7

One was released 3 days ago:
https://github.com/sherter/google-java-format-gradle-plugin/releases/tag/v0.9

So setting the version to `0.8` here: https://github.com/tomasbjerre/gradle-scripts/blob/master/src/main/resources/java.gradle#L7
might fix it.

**Comment by remal** [comment]
Looks like it's not google-java-format-gradle-plugin, it's google-java-format tool itself. Take a look at release 1.8: https://github.com/google/google-java-format/releases/tag/google-java-format-1.8
> The minimum supported runtime version is now JDK 11.

**Comment by tomasbjerre** [comment]
fixed: https://travis-ci.org/github/tomasbjerre/violations-lib/builds
https://github.com/tomasbjerre/gradle-scripts/commit/a3df39dc84c4973c82f444154974a1d1dcd8294a

You can get the latest script by doing `./gradlew build --refresh-dependencies`
